import type { Metadata } from "next";
import "./globals.css";
import AuthSessionProvider from "@/components/providers/SessionProvider";
import ToasterProvider from "@/components/providers/ToasterProvider";
import { inter , jakarta } from "./font";



export const metadata: Metadata = {
  title: "Vualá | plataforma de entregas de  última milla ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${jakarta.variable}`}>
      <body
        className="font-jakarta"
      >
        <AuthSessionProvider>
          <ToasterProvider />
          {children}
        </AuthSessionProvider>
      </body>
    </html>
  );
}
